approve:
- commandHelpLink: ""
  repos:
  - openshift/kubernetes-cloud-provider
  require_self_approval: true
label:
  restricted_labels:
    openshift/kubernetes-cloud-provider:
    - allowed_users:
      - JoelSpeed
      - elmiko
      - Fedosin
      - lobziik
      - damdo
      label: backport-risk-assessed
    - allowed_users:
      - sunzhaohua2
      - miyadav
      - jhou1
      - huali9
      label: cherry-pick-approved
lgtm:
- repos:
  - openshift/kubernetes-cloud-provider
plugins:
  openshift/kubernetes-cloud-provider:
    plugins:
    - approve
