build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-8-release-golang-1.19-openshift-4.12
canonical_go_repository: k8s.io/cloud-provider
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: go test ./...
  container:
    from: src
zz_generated_metadata:
  branch: master
  org: openshift
  repo: kubernetes-cloud-provider
